#!/bin/sh /etc/rc.common
#Author:ferstar
#Email:zhangjianfei3@gmail.com

START=55
STOP=10

start()
{
if [ $(uci get njit-client.@option[0].enable) ] ;
then
	njit-client $(uci get njit-client.@njit-client[0].Username) $(uci get njit-client.@njit-client[0].Password) eth0.2 &
else
	stop
fi

if [ $(uci get njit-client.@option[0].boot) ] ;
then
	/etc/init.d/njit-client enable
else
	/etc/init.d/njit-client disable
fi
}

stop()
{
sync
njit-client -k >/dev/null 2>&1
}

restart()
{
stop
start
}
